// Generated by Wrangler on Sun Aug 04 2024 21:51:47 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	AUTH_KEY: string;
	USER_DATA_AUTHORISATION_KEY: string;
	DB: D1Database;
	USER_DATA: Fetcher;
}
