// Generated by Wrangler on Thu Aug 08 2024 16:23:00 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	USER_CREATION_AUTH_KEY: "USER CREATION AUTH KEY";
	AUTH_KEY: string;
	USER_DATA_AUTHORISATION_KEY: string;
	USER_ID_AUTH_KEY: string;
	DB: D1Database;
	USER_DATA: Fetcher;
}
